server:
  port: 8080

spring:
  application:
    name: 'order-service'

  cloud:
    function:
      definition: createOrder
    stream:
      bindings:
        createOrder-in-0:
          destination: create_order
      kafka:
        binder:
          auto-create-topics: true
          brokers: localhost:9092

  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: non_null

  datasource:
    driver-class-name: org.postgresql.Driver
    name: orders
    password: orders_pass
    username: orders_admin
    url: jdbc:postgresql://localhost:5432/${spring.datasource.name}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true

    open-in-view: false

  sql:
    init:
      platform: h2
      mode: embedded

# logging settings
logging:
  level:
    root: info
    com: warn
    org:
      apache: warn
      hibernate: warn
      springframework: error

  pattern:
    console: '%clr([%date{HH:mm:ss.SSS}]){faint} %clr(%2p) %clr(%-40.40logger{36}){cyan} %m%n%wex'